#!/bin/bash

# (c) SRON - Netherlands Institute for Space Research (2014).
# All Rights Reserved.
# This software is distributed under the BSD 2-clause license.

## === Variables ===============================================================

varLogin=`whoami`
targetdir=/data/local/users/${varLogin}/results/quicklooks

## === Processing ==============================================================

## check if the target directory exists; if this is not the case, create it

if [ ! -d "$targetdir" ]; then
  mkdir -p ${targetdir}
fi

## Copy the quicklooks files

for FILE in `ls`
{
    for PLOT in quicklook_detector quicklook_raw quicklook_scanning_all quicklook_scanning_all_mask quicklook_scanning_maximum quicklook_scanning_row
    {
        varSource=${FILE}/${PLOT}/quicklook_detector4.pdf
        # check of quicklooks file is actually there
        if [[ -f ${varSource} ]] ; then
        {
             echo " - Copying ${varSource}"
             cp ${varSource} ${targetdir}/${FILE}.${PLOT}.pdf
        }
        fi
    }
}
